openapi: 3.1.0
info:
  title: Sample API
  description: API documentation for the Sample project
  version: 1.0.0
servers:
  - url: http://petstore.swagger.io/v2 
paths:
   /store/inventory:
    get:
      summary: Get a list of users
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: integer
                  format: int32
